### ISSUE TITLE
Can't import templates on cacti 1.1.30

### ISSUE THREAD

**Issue by woj1965** [glenpp/cacti-uloganalyser#9]
Hello!
I using cacti 1.1.30 and I can't import templates, I have no error messages or feedback when I try it.
Is there anything I need to do?
Thanks.

**Comment by glenpp** [comment]
As I deliberately use older well proven releases which newer releases should theoretically have backwards compatibility with, this is not something I'm going to be able to help with, and stats suggest there's a respectable number of people using these templates. These kinds of problems seem all too common with releases that haven't yet been proven on the battlefield. Beyond the usual things for debugging like turning up the logging, I think this would be more appropriate to discuss in Cacti support forums.

Please also avoid cross-posting.
